title: Chaoqi LIU
logo: /photos/logo.jpeg
description: "I skate to where the puck is going, not where it has been"
remote_theme: BDHU/minimalist
color-scheme: auto

sidebar:
  - name: -> Hômèpägé
    link: https://chaoqi-liu.github.io
  - name: -> Èdūçãtįøñ
    link: https://chaoqi-liu.github.io/education/overview
  - name: -> Èxpèrîéñçē
    link: https://chaoqi-liu.github.io/experience/overview
  - name: -> Hôñörš & Ãwàrdś
    link: https://chaoqi-liu.github.io/honors&awards

