title: Chaoqi LIU
logo: /photos/logo.jpeg
favicon: true
description: "I skate to where the puck is going, not where it has been"
remote_theme: BDHU/minimalist
color-scheme: auto

sidebar:
  - name: Navigation bar
  - name: Homepage
    link: https://chaoqi-liu.github.io
  - name: Education
    link: https://chaoqi-liu.github.io/education/overview
  - name: Experience
    link: https://chaoqi-liu.github.io/experience/overview
  - name: Honors & Awards
    link: https://chaoqi-liu.github.io/honors&awards

